### PR TITLE
Maintain draft editing context

### LINKED ISSUE #22: Wrong this.editTitle in a section
We have a fishing plugin [https://github.com/oflg/fishing](https://github.com/oflg/fishing) that you may know. We use `this.editTitle` to get current article tiddler's title, and add the a article title as tag for the flashcard.

But currently, in a section, the `this.editTitle` will be wrong, seem to be changed to the first line section?

### PR DESCRIPTION
**Pull request by linonetwo**
This might fix #22

### CODE REVIEW

**Comment by linonetwo** [comment]
Bad news, if a tiddler have draft.xxx field, there will be a red item on the bottom left...

Old behavior:



After I add draft.xxx:

**Comment by linonetwo** [comment]
Fixed by removing `<$action-setfield $tiddler=<<editTid>> $field="draft.of" $value={{{ [<currentTiddler>get[title]] }}} />`

Now it works pretty well.

**Comment by kookma** [comment]
@linonetwo 
Are you working on this branch? I see some new commits, but I did not find the explanations

**Comment by linonetwo** [comment]
Oh, I was just rebase it on the main branch. And I build one for my wiki to use...

**Pull request closed without merging**
